Router.configure({
    layoutTemplate:'main_layout'
});
Router.map(function(){
    this.route('login',{
        path:'/',
        template:'login'
    }),
    this.route('register',{
        path:'/register',
        template:'register'
    }),
    this.route('dashboard',{
        path:'/dashboard',
        template:'dashboard'
    }),
    this.route('profile',{
        path:'/profile',
        template:'profile'
    })
})